version: '3'
services:
    mariadb-db:
        image: mariadb:11.1
        volumes:
          - ./db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: hogehoge123